### ISSUE TITLE
Cannot resolve module 'redux-form'

### ISSUE THREAD

**Issue by CrazyCompiler** [catalin-luntraru/redux-minimal#11]

**Comment by catalin-luntraru** [comment]
Then you better install redux-form

`npm install --save redux-form`

**Comment by catalin-luntraru** [comment]
Le me know if that worked for you, so I can close the issue.

**Comment by ChrisMacpherson** [comment]
I know this is closed but this will help anyone who comes across this problem (like me 😄).

Read the top section of this page:

https://redux-form.com/7.4.2/docs/flow.md/
