### ISSUE TITLE
Uncaught TypeError: validator is not a function(…)

### ISSUE THREAD

**Issue by rhengeveld** [catalin-luntraru/redux-minimal#12]
Hello,

I've run into some issues while trying to get this starter kit to work as per the installation instructions. Sadly I have no idea what to do or what went wrong, so could I please get some fix/directions?

## 1) Application is not at localhost:8080?

I followed the default (master branch) installation instructions. After `npm start` I can not find the app at `http://localhost:8080`, but it's at `http://127.0.0.1:8080`? That's odd.

```
MacBook-Pro:hello-world-webpack hengeveld$ lsof -n -i4TCP:8080 | grep LISTEN
node    1050 hengeveld   18u  IPv4 <snip>      0t0  TCP 127.0.0.1:http-alt (LISTEN)
```

In addition I tried to change the port to 8000, but this change isn't picked up?
```
// @entry webpack.config.js
'webpack-dev-server/client?http://localhost:8000',
```

## 2) Uncaught TypeError: validator is not a function(…)

Ok, so I found the app at another address. Let's try to work with that! 

Sadly, the form validation at `UserEdit` seems broken 😞 
```
bundle.js:45943 Uncaught TypeError: validator is not a function(…)
```
The _validator_ in this instance is the _true boolean_. Removing `validate={true}` from the _username_ Field removes the error, but also the validation error message if you leave the field empty. Ugh, I have no idea how to fix this.

**Comment by rhengeveld** [comment]
The validator error goes away when I use the [1.1.0 release](https://github.com/catalin-luntraru/redux-minimal/releases/tag/1.1.0). I guess the refactoring broke this 😕

**Comment by rhengeveld** [comment]
Per [this SO issue](http://stackoverflow.com/questions/33272967/how-to-make-the-webpack-dev-server-run-on-port-80-and-on-0-0-0-0-to-make-it-publ) I've changed webpack config to work on localhost:8000. 

So I guess both issues are be fixed - however this starter kit currently doesn't work out of the box using the provided instructions.

**Comment by catalin-luntraru** [comment]
Hey @rhengeveld 
I see other people tried changing the host and/or port so now you can do so easily. I also updated the documentation so people know this is possible https://github.com/catalin-luntraru/redux-minimal#change-host-andor-port

I fixed the validator issue. Somehow redux-form didn't like the validate property of the FormField so I changed it to doValidate.

Feel free to checkout the latest code and see if it works for you.
