### ISSUE TITLE
Hot reload not working - full refresh, lost state

### ISSUE THREAD

**Issue by anjdreas** [catalin-luntraru/redux-minimal#14]
Hi, I tried the app as-is, but when modifying text in the footer or any other trivial change to the source code I get a full refresh of the app, with the bootstrap progress bar, and state like the user list is reset back to the initial state.

Is this a known issue, or do you know how this can be fixed?

**Comment by catalin-luntraru** [comment]
Reverted to the stable version of react-hot-loader. Also updated all packages.
