### ISSUE TITLE
User add form does not reset

### ISSUE THREAD

**Issue by tw3** [catalin-luntraru/redux-minimal#15]
If you are on the User edit page and you navigate to the Users add page the form does not reset.  The edit user data still shows.

**Comment by tw3** [comment]
I think the problem is that redux-form looks for the form component to unmount before it destroys and re-initializes the form.  Since the form component does not unmount from the User edit to User add page there is no unmount and thus no reset.

Some fixes to reset the form are discussed here:

[How can I clear my form after my submission succeeds?](http://redux-form.com/6.0.0-alpha.4/docs/faq/HowToClear.md/)

I went with approach A which involved this code change in `src_users/reducers/index.js`:

```javascript
// main reducers
export const reducers = combineReducers({
  routing: routerReducer,
  form: formReducer.plugin({
		"user_edit": (state, action) => {
			// reset form (wipe state) when navigating away from the User edit page
			switch(action.type) {
				case "@@router/LOCATION_CHANGE":
					return undefined;
				default:
					return state;
			}
		}
	}),
  scheduledEvents: scheduledEvents
});
```

There might be cases where this is bad, e.g. if you (for some reason) change the location but don't want to reset the form.  This doesn't seem plausible though.

**Comment by catalin-luntraru** [comment]
Thanks. I have applied the fix and it worked great.

The `dispatch(reset('user_edit'))` would have been nicer, but unfortunately react-router doesn't remount the component when the url changes.

Cool fix
