### ISSUE TITLE
Deployment Strategies?

### ISSUE THREAD

**Issue by MattReimer** [catalin-luntraru/redux-minimal#16]
I'm trying to figure out how to deploy this on a fresh production machine. Eventually, I'd like to try to get this dockerized but I'm not there yet.

My trouble is that `webpack` is in the dev dependencies so I can't seem to get build-prod to run with `NODE_ENV=production`

These are the steps I'm running:

```
npm install
npm run build-prod
npm start
```

And then it should work like a daemon right? I feel like I'm missing something here.

**Comment by catalin-luntraru** [comment]
Have a look at the documentation where it explains all the npm scripts https://github.com/catalin-luntraru/redux-minimal#scripts

So only the `start` script launches a server (`webpack-dev-server`) and gives you access to http://localhost:8080. The other scripts `build-dev` and `build-prod` only creates the js and css file bundles without any server running in the background.

Let's say you want to push your site to a server. You would run `build-dev` or`build-prod` to generate the css/js files and then copy the entire app public folder somewhere on your server. This is what I did for the demo at http://redux-minimal-app.catalin-luntraru.com/

If you want to use a server to run the files, then check the [`express branch`](https://github.com/catalin-luntraru/redux-minimal/tree/express) which uses node.js and express to serve the files. Here you have `start`  and `start-prod` which builds the css/js files and also serves the app at http://localhost:8080

**Comment by MattReimer** [comment]
Thanks. That cleared things up. I was trying to build AND run on the production machine and, of course, that wasn't working. `start-prod` looks interesting too.

**Comment by awb99** [comment]
I don't understand why there is a separate branch that I need to call, so that I can run redux-minimal in production.  

Am I right, that  the production build is there, so that it is easy to integrate a react application into a bigger express powered site?

Thanks! Andreas
