### ISSUE TITLE
Need support for images/icons to get loaded from sass files

### ISSUE THREAD

**Issue by sdn2525** [catalin-luntraru/redux-minimal#19]
I created a images folder and added few classes on main.scss  with `background: url('../images/pc-logo.png')` property but i get errors

```
ERROR in ./~/css-loader!./~/sass-loader!./src/stylesheets/main.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ../images/icons/pc-logo.png
```

**Comment by catalin-luntraru** [comment]
I have added an example of using a background image inside a sass file. It's very easy to do it, just add your image inside the media folder and then reference it in the sass file as `background-image: url('/media/pattern.jpg');`
